Find and print the indices of pairs of elements in the following array “a” for which the value of their sum is a multiple of 7.

a = np.array([1, 7, 3, 10, 14, 76, 4])

In [1]:
import numpy as np

a = np.array([1, 7, 3, 10, 14, 76, 4])
for i in range(len(a)):
    for j in range(i + 1, len(a)):
        if (a[i] + a[j]) % 7 == 0:
            print((i, j))

(0, 5)
(1, 4)
(2, 6)
(3, 6)


Calculate the inverse of matrix A (save it as A_inv) and its dot product and element-wise multiplication with B using NumPy.

    A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])
    B = np.array([[5, 6, 7],[7, 8, 9],[1, 2, 3]])


In [2]:
import numpy as np

A = np.array([[1, 2, 0],
              [0, 5, 6],
              [7, 0, 9]])

B = np.array([[5, 6, 7],
              [7, 8, 9],
              [1, 2, 3]])

# Inverse of A
A_inverse = np.linalg.inv(A)

# Dot product
dot_product = np.dot(A, B)

# Element-wise multiplication
element_wise = A * B

print("A inverse:")
print(A_inverse)

print("\nDot Product:")
print(dot_product)

print("\nElement-wise Multiplication:")
print(element_wise)

A inverse:
[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]

Dot Product:
[[19 22 25]
 [41 52 63]
 [44 60 76]]

Element-wise Multiplication:
[[ 5 12  0]
 [ 0 40 54]
 [ 7  0 27]]



A NumPy array “data” is given as follows:

data = np.array([
[1, 2, 3, 4, 5],
[1, 8, 2, 10, 11],
[4, 5, 6, 7, 8],
[7, 8, 9, 10, 11],
[7, 18, 19, 10, 11]])

Do the following

a)Create a dataframe as df for the NumPy array “data” with column name {A,B,C,D,E}.

b)Sort the dataframe based on column C and save it as df2. Prints the first two and last two rows of the dataframe df2 using df2.head and df2.tail.

c)Print the df2 values only as NumPy array.

In [3]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3, 4, 5],
                 [1, 8, 2, 10, 11],
                 [4, 5, 6, 7, 8],
                 [7, 8, 9, 10, 11],
                 [7, 18, 19, 10, 11]])

# a) Create DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D', 'E'])

print("DataFrame:")
print(df)

# b) Sort based on column C
df2 = df.sort_values(by='C')

print("\nFirst two rows:")
print(df2.head(2))

print("\nLast two rows:")
print(df2.tail(2))

# c) Convert df2 to NumPy array
print("\nNumPy Array:")
print(df2.values)

DataFrame:
   A   B   C   D   E
0  1   2   3   4   5
1  1   8   2  10  11
2  4   5   6   7   8
3  7   8   9  10  11
4  7  18  19  10  11

First two rows:
   A  B  C   D   E
1  1  8  2  10  11
0  1  2  3   4   5

Last two rows:
   A   B   C   D   E
3  7   8   9  10  11
4  7  18  19  10  11

NumPy Array:
[[ 1  8  2 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]


Compute the eigen values the matrix A using np.linalg.eig . Find the spectral radius of the matrix A.

A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])

In [4]:
import numpy as np

A = np.array([[1, 2, 0],
              [0, 5, 6],
              [7, 0, 9]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

spectral_radius = np.max(np.abs(eigenvalues))

print("\nSpectral Radius:")
print(spectral_radius)

Eigenvalues:
[10.5740355 +0.j          2.21298225+2.70229602j  2.21298225-2.70229602j]

Spectral Radius:
10.57403549813147


Consider the matrix
              B = np.array([[5, 6, 7], [7, 8, 9], [1, 2, 3]])  ;   Using NumPy, answer the following:

(a) Compute the SVD.
 Use np.linalg.svd(B, full_matrices=False) to obtain the matrices U, S, and Vt. Convert the one-dimensional array S into a diagonal matrix Sigma = np.diag(S).

(b) Reconstruct the original matrix as B_recon = U @ Sigma @ Vt. Test the accuracy of the reconstruction with np.allclose(B, B_recon, atol=1e-10) and report the Boolean result.

(c) Using the singular values in S, compute the spectral (2-norm) condition number
κ2B=σmaxσmin
    Print the value of κ2B


In [5]:
import numpy as np

B = np.array([[5, 6, 7],
              [7, 8, 9],
              [1, 2, 3]])

# (a) SVD
U, S, Vt = np.linalg.svd(B, full_matrices=False)

Sigma = np.diag(S)

print("U =")
print(U)

print("\nS =")
print(S)

print("\nSigma =")
print(Sigma)

print("\nVt =")
print(Vt)

# (b) Reconstruction
B_recon = U @ Sigma @ Vt

print("\nReconstructed B =")
print(B_recon)

print("\nReconstruction Accurate?")
print(np.allclose(B, B_recon, atol=1e-10))

# (c) Condition Number
kappa_2_B = S.max() / S.min()

print("\nCondition Number (kappa_2(B)) =")
print(kappa_2_B)

U =
[[-0.58909693  0.10053691 -0.80178373]
 [-0.78215124 -0.32019549  0.53452248]
 [-0.20298829  0.94200169  0.26726124]]

S =
[1.78028049e+01 1.02963004e+00 1.47181129e-15]

Sigma =
[[1.78028049e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02963004e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.47181129e-15]]

Vt =
[[-0.48439174 -0.57281806 -0.66124437]
 [-0.77375576 -0.07219979  0.62935619]
 [ 0.40824829 -0.81649658  0.40824829]]

Reconstructed B =
[[5. 6. 7.]
 [7. 8. 9.]
 [1. 2. 3.]]

Reconstruction Accurate?
True

Condition Number (kappa_2(B)) =
1.2095847478372948e+16
